export const BLACK_DIRECTED_MOVIES = [
  "Do the Right Thing", "Moonlight", "Get Out", "Boyz n the Hood", "Fruitvale Station",
  "Selma", "Black Panther", "12 Years a Slave", "Malcolm X", "Creed",
  "Straight Outta Compton", "Us", "Fences", "Precious", "Daughters of the Dust",
  "Pariah", "Killer of Sheep", "Eve's Bayou", "Menace II Society", "Love & Basketball",
  "Waiting to Exhale", "Set It Off", "Friday", "Crooklyn", "Juice",
  "The Last Black Man in San Francisco", "Mudbound", "If Beale Street Could Talk", "Dope", "Bessie",
  "Bamboozled", "Belly", "Clockers", "Chi-Raq", "Da 5 Bloods",
  "Shaft", "Candyman", "Soul Food", "The Best Man", "Higher Learning",
  "Poetic Justice", "New Jack City", "Boomerang", "Just Mercy", "Queen & Slim",
  "The Wood", "Brown Sugar", "Hustle & Flow", "Talk to Me", "Akeelah and the Bee",
  "Drumline", "ATL", "Paid in Full", "The Inevitable Defeat of Mister & Pete", "Middle of Nowhere",
  "Beyond the Lights", "The Secret Life of Bees", "Jumping the Broom", "Cadillac Records", "Southside with You",
  "The Photograph", "The Forty-Year-Old Version", "Miss Juneteenth", "Night Catches Us", "Atlantics",
  "Girlhood", "Rocks", "The Last Tree", "Rafiki", "Farming",
  "Noughts + Crosses", "The Boy Who Harnessed the Wind", "Queen of Katwe", "Beasts of No Nation", "Tsotsi",
  "Atlantique", "Yeelen", "Touki Bouki", "Black Girl", "Hyenas",
  "Moolaadé", "Bamako", "Timbuktu", "Félicité", "I Am Not a Witch",
  "Vaya", "Inxeba (The Wound)", "Kati Kati", "Supa Modo", "Rafiki",
  "Yardie", "The Kitchen", "Clemency", "The Burial of Kojo", "Eyimofe (This Is My Desire)",
  "Residue", "Nine Days", "Zola", "Passing", "The Harder They Fall"
] 